#ifndef _codes_h_
#define _codes_h_ 1

enum InterruptCodes {
    INTERRUPT_SIGNIFIER = 0x100,
    INTERRUPT_TIMER_C1 = 97,
    INTERRUPT_TIMER_C3 = 99,
    INTERRUPT_UART = 153,
    INTERRUPT_UART_CONSOLE,
    INTERRUPT_UART_MARKLIN
};

enum SystemCallCodes {
    SYSCALL_EXIT = 0x01,
    SYSCALL_YIELD,
    SYSCALL_MY_PARENT_TID,
    SYSCALL_MY_TID,
    SYSCALL_CREATE,
    SYSCALL_SEND = 0x11,
    SYSCALL_RECEIVE,
    SYSCALL_REPLY,
    SYSCALL_REGISTER_AS = 0x21,
    SYSCALL_WHO_IS,
    SYSCALL_AWAIT_EVENT = 0x31,
    SYSCALL_TIME = 0x41,
    SYSCALL_DELAY,
    SYSCALL_DELAY_UNTIL,
    SYSCALL_GETC = 0x51,
    SYSCALL_PUTC
};

#endif